import { useState, useEffect } from "react";
import {
  Heading,
  Text,
  Link,
  Button,
  Stack,
  Flex,
  Avatar,
  Box,
} from "@chakra-ui/react";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";
import { setupEventListener } from "../utils/mintContract";

export default function Home() {
  const [isWalletAvailable, setIsWalletAvailable] = useState(true);
  const [currentAccount, setCurrentAccount] = useState("");

  const router = useRouter();

  const checkIfWalletIsConnected = async () => {
    const { ethereum } = window;
    Boolean(ethereum)
      ? setIsWalletAvailable(true)
      : setIsWalletAvailable(false);

    const accounts = await ethereum.request({ method: "eth_accounts" });

    if (accounts.length) {
      setCurrentAccount(accounts[0]);
      setupEventListener();
    }
  };

  const connectWallet = async () => {
    try {
      const accounts = await ethereum.request({
        method: "eth_requestAccounts",
      });
      setCurrentAccount(accounts[0]);
      setupEventListener();
    } catch (error) {
      console.error(error.message);
    }
  };

  useEffect(() => {
    checkIfWalletIsConnected();
  }, []);

  const renderConnectButton = () => {
    return (
      <Stack margin="10px 0">
        {currentAccount ? (
          <Button onClick={() => router.push("/upload")} colorScheme="teal">
            Upload &amp; Mint
          </Button>
        ) : (
          <Button onClick={connectWallet} colorScheme="teal">
            Connect your wallet
          </Button>
        )}
      </Stack>
    );
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {currentAccount && (
        <nav>
          <Flex margin="10px 0" justifyContent="flex-end">
            <Flex
              borderWidth="1px"
              borderColor="gray.400"
              alignItems="center"
              padding="5px"
              borderRadius="30px"
            >
              <Avatar size="sm" bg="teal.500" />
              <Text padding="0 10px">{currentAccount}</Text>
            </Flex>
          </Flex>
        </nav>
      )}

      <main className={styles.main}>
        <Heading className={styles.title}>
          Welcome to CodePunk.
          <Text as="span" color="teal.500">
            nft
          </Text>
        </Heading>

        <Stack margin="50px 0">
          <Image
            src="/assets/ethereum-illustration.svg"
            width="200px"
            height="300px"
          />
        </Stack>

        {isWalletAvailable ? (
          renderConnectButton()
        ) : (
          <Text className={styles.description}>
            It looks like you do not have the wallet installed. <br />
            Follow this{" "}
            <Link
              color="blue.500"
              href="https://metamask.io/download.html"
              isExternal
            >
              link to install Metamask
            </Link>{" "}
            in your browser.
          </Text>
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
